add isunix in jenkinsfile

diff --git a/reactapp/Jenkinsfile b/reactapp/Jenkinsfile
--- a/reactapp/Jenkinsfile
+++ b/reactapp/Jenkinsfile
@@ -1,63 +1,50 @@
 pipeline {
     agent any
 
-    environment {
-        IMAGE_NAME = 'blog_nextjs_app'
-        CONTAINER_NAME = 'blog_nextjs_container'
-        PORT = '3000'
-    }
-
     stages {
-        stage('Checkout') {
-            steps {
-                git branch: 'main', url: 'https://github.com/jjoevv/blog_nextjs.git'
-            }
-        }
-
         stage('Install Dependencies') {
             steps {
-                sh 'npm install'
+                script {
+                    if (isUnix()) {
+                        sh 'npm install'
+                    } else {
+                        bat 'npm install'
+                    }
+                }
             }
         }
 
-        stage('Build Next.js') {
+        stage('Build') {
             steps {
-                sh 'npm run build'
+                script {
+                    if (isUnix()) {
+                        sh 'npm run build'
+                    } else {
+                        bat 'npm run build'
+                    }
+                }
             }
         }
 
         stage('Test') {
             steps {
-                sh 'npm test || true'
-            }
-        }
-
-        stage('Build Docker Image') {
-            steps {
-                sh "docker build -t $IMAGE_NAME ."
-            }
-        }
-
-        stage('Run Docker Container') {
-            steps {
-                // Stop previous container if exists
-                sh "docker rm -f $CONTAINER_NAME || true"
-                // Run new container
-                sh "docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $IMAGE_NAME"
+                script {
+                    if (isUnix()) {
+                        sh 'npm test || true'
+                    } else {
+                        bat 'npm test || exit 0'
+                    }
+                }
             }
         }
     }
 
     post {
-        always {
-            archiveArtifacts artifacts: 'out/**', allowEmptyArchive: true
-            junit '**/test-results.xml'
-        }
         success {
-            echo '✅ Build & deploy completed successfully!'
+            echo '✅ Build success!'
         }
         failure {
-            echo '❌ Pipeline failed!'
+            echo '❌ Build failed!'
         }
     }
 }
